services:
  # Static site for React frontend
  - type: web
    name: math-game-client
    runtime: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: NODE_VERSION
        value: 20.x

  # Backend API service
  - type: web
    name: math-game-api
    runtime: node
    buildCommand: cd server && npm install
    startCommand: cd server && node src/index.js
    envVars:
      - key: NODE_VERSION
        value: 20.x